on:
    push:
        tags:
            - 'v*.*.*'

name: compile

jobs:
    build:
        name: Linux Build
        runs-on: ubuntu-latest
        steps:
            -   name: set var current tag
                id: vars
                run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            -   uses: actions/checkout@v2
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   uses: docker/setup-buildx-action@v1
                id: buildx
                with:
                    install: true
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Build and push
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    docker buildx build --platform linux/arm64,linux/amd64 -t timglabisch/elasticsearch245:${{ steps.vars.outputs.tag }} --push .